package api

import (
	"fmt"
	"net/http"

	"aetherflow/services"

	"github.com/gin-gonic/gin"
)

// HandleDeployStream upgrades a standard request to a Server-Sent Events stream
// tracking the live lifecycle logs of an AetherFlow Blueprint execution or Blue/Green swap.
func HandleDeployStream(c *gin.Context) {
	appName := c.Query("appName")
	if appName == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "appName query parameter is required"})
		return
	}

	// Upgrade the HTTP sequence to text/event-stream
	c.Writer.Header().Set("Content-Type", "text/event-stream")
	c.Writer.Header().Set("Cache-Control", "no-cache")
	c.Writer.Header().Set("Connection", "keep-alive")
	// Allow bypassing buffer for instant feedback
	c.Writer.Header().Set("X-Accel-Buffering", "no") 

	// Retrieve the active stream explicitly generated by the orchestrator initialization.
	streamChan := services.StreamHub.GetStream(appName)
	if streamChan == nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "No active deployment found for this application."})
		return
	}

	notify := c.Request.Context().Done()

	// Spin event loop bridging Go channels to chunked HTTP chunks
	for {
		select {
		case <-notify:
			// Browser connection cut or user navigated away. Wait for defer closure natively.
			return
			
		case msg, ok := <-streamChan:
			if !ok {
				// The orchestrator closed the channel on termination (Success or Validation Failure)
				return
			}
			// Write the SSE payload template.
			fmt.Fprintf(c.Writer, "data: %s\n\n", msg)
			c.Writer.Flush()
		}
	}
}
