// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/cluster.proto
//
// NOTE: This file was manually scaffolded based on cluster.proto.
// To regenerate from proto, run:
//   protoc --go_out=. --go-grpc_out=. proto/cluster.proto

package pb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// --- Message Types ---

type SystemInfo struct {
	Os               string `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch             string `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	CpuCores         int32  `protobuf:"varint,3,opt,name=cpu_cores,proto3" json:"cpu_cores,omitempty"`
	TotalMemoryBytes int64  `protobuf:"varint,4,opt,name=total_memory_bytes,proto3" json:"total_memory_bytes,omitempty"`
	TotalDiskBytes   int64  `protobuf:"varint,5,opt,name=total_disk_bytes,proto3" json:"total_disk_bytes,omitempty"`
}

type RegisterRequest struct {
	Hostname   string      `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Address    string      `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Psk        string      `protobuf:"bytes,3,opt,name=psk,proto3" json:"psk,omitempty"`
	Version    string      `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	SystemInfo *SystemInfo `protobuf:"bytes,5,opt,name=system_info,proto3" json:"system_info,omitempty"`
}

type RegisterResponse struct {
	NodeId   string `protobuf:"bytes,1,opt,name=node_id,proto3" json:"node_id,omitempty"`
	Accepted bool   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message  string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

type WorkerMetrics struct {
	CpuUsage       float64   `protobuf:"fixed64,1,opt,name=cpu_usage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsedGb   float64   `protobuf:"fixed64,2,opt,name=memory_used_gb,proto3" json:"memory_used_gb,omitempty"`
	MemoryTotalGb  float64   `protobuf:"fixed64,3,opt,name=memory_total_gb,proto3" json:"memory_total_gb,omitempty"`
	DiskUsedGb     float64   `protobuf:"fixed64,4,opt,name=disk_used_gb,proto3" json:"disk_used_gb,omitempty"`
	DiskTotalGb    float64   `protobuf:"fixed64,5,opt,name=disk_total_gb,proto3" json:"disk_total_gb,omitempty"`
	NetworkRxSpeed string    `protobuf:"bytes,6,opt,name=network_rx_speed,proto3" json:"network_rx_speed,omitempty"`
	NetworkTxSpeed string    `protobuf:"bytes,7,opt,name=network_tx_speed,proto3" json:"network_tx_speed,omitempty"`
	Uptime         string    `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`
	LoadAverage    []float64 `protobuf:"fixed64,9,rep,packed,name=load_average,proto3" json:"load_average,omitempty"`
}

type ServiceStatus struct {
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status    string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Uptime    string `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	ManagedBy string `protobuf:"bytes,4,opt,name=managed_by,proto3" json:"managed_by,omitempty"`
}

type HeartbeatPing struct {
	NodeId    string           `protobuf:"bytes,1,opt,name=node_id,proto3" json:"node_id,omitempty"`
	Timestamp int64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics   *WorkerMetrics   `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Services  []*ServiceStatus `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
}

type HeartbeatPong struct {
	Timestamp    int64          `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Acknowledged bool           `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	Command      *RemoteCommand `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
}

type RemoteCommand struct {
	Id     string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type   string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Params map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type MetricsRequest struct {
	NodeId           string `protobuf:"bytes,1,opt,name=node_id,proto3" json:"node_id,omitempty"`
	IncludeProcesses bool   `protobuf:"varint,2,opt,name=include_processes,proto3" json:"include_processes,omitempty"`
	IncludeDisks     bool   `protobuf:"varint,3,opt,name=include_disks,proto3" json:"include_disks,omitempty"`
}

type ProcessInfo struct {
	Pid        int32   `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name       string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CpuPercent float64 `protobuf:"fixed64,3,opt,name=cpu_percent,proto3" json:"cpu_percent,omitempty"`
	MemPercent float64 `protobuf:"fixed64,4,opt,name=mem_percent,proto3" json:"mem_percent,omitempty"`
}

type DiskInfo struct {
	MountPoint string  `protobuf:"bytes,1,opt,name=mount_point,proto3" json:"mount_point,omitempty"`
	Device     string  `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	FsType     string  `protobuf:"bytes,3,opt,name=fs_type,proto3" json:"fs_type,omitempty"`
	TotalGb    float64 `protobuf:"fixed64,4,opt,name=total_gb,proto3" json:"total_gb,omitempty"`
	UsedGb     float64 `protobuf:"fixed64,5,opt,name=used_gb,proto3" json:"used_gb,omitempty"`
	FreeGb     float64 `protobuf:"fixed64,6,opt,name=free_gb,proto3" json:"free_gb,omitempty"`
	UsedPct    float64 `protobuf:"fixed64,7,opt,name=used_pct,proto3" json:"used_pct,omitempty"`
}

type MetricsResponse struct {
	NodeId    string           `protobuf:"bytes,1,opt,name=node_id,proto3" json:"node_id,omitempty"`
	Metrics   *WorkerMetrics   `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Services  []*ServiceStatus `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	Processes []*ProcessInfo   `protobuf:"bytes,4,rep,name=processes,proto3" json:"processes,omitempty"`
	Disks     []*DiskInfo      `protobuf:"bytes,5,rep,name=disks,proto3" json:"disks,omitempty"`
}

type CommandRequest struct {
	NodeId    string            `protobuf:"bytes,1,opt,name=node_id,proto3" json:"node_id,omitempty"`
	CommandId string            `protobuf:"bytes,2,opt,name=command_id,proto3" json:"command_id,omitempty"`
	Type      string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Params    map[string]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

type CommandResponse struct {
	CommandId string `protobuf:"bytes,1,opt,name=command_id,proto3" json:"command_id,omitempty"`
	Success   bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output    string `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error     string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

// --- Service Interface ---

// ClusterServiceClient is the client API for ClusterService.
type ClusterServiceClient interface {
	RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (ClusterService_HeartbeatClient, error)
	GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error)
	ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
}

type clusterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterServiceClient(cc grpc.ClientConnInterface) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) RegisterWorker(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/RegisterWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (ClusterService_HeartbeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName:    "Heartbeat",
		ServerStreams:  true,
		ClientStreams:  true,
	}, "/cluster.ClusterService/Heartbeat", opts...)
	if err != nil {
		return nil, err
	}
	return &clusterServiceHeartbeatClient{stream}, nil
}

type ClusterService_HeartbeatClient interface {
	Send(*HeartbeatPing) error
	Recv() (*HeartbeatPong, error)
	grpc.ClientStream
}

type clusterServiceHeartbeatClient struct {
	grpc.ClientStream
}

func (x *clusterServiceHeartbeatClient) Send(m *HeartbeatPing) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clusterServiceHeartbeatClient) Recv() (*HeartbeatPong, error) {
	m := new(HeartbeatPong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clusterServiceClient) GetMetrics(ctx context.Context, in *MetricsRequest, opts ...grpc.CallOption) (*MetricsResponse, error) {
	out := new(MetricsResponse)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/GetMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) ExecuteCommand(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/ExecuteCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// --- Server Interface ---

// ClusterServiceServer is the server API for ClusterService.
type ClusterServiceServer interface {
	RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Heartbeat(ClusterService_HeartbeatServer) error
	GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error)
	ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error)
}

// UnimplementedClusterServiceServer should be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct{}

func (UnimplementedClusterServiceServer) RegisterWorker(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedClusterServiceServer) Heartbeat(ClusterService_HeartbeatServer) error {
	return status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedClusterServiceServer) GetMetrics(context.Context, *MetricsRequest) (*MetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedClusterServiceServer) ExecuteCommand(context.Context, *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}

type ClusterService_HeartbeatServer interface {
	Send(*HeartbeatPong) error
	Recv() (*HeartbeatPing, error)
	grpc.ServerStream
}

type clusterServiceHeartbeatServer struct {
	grpc.ServerStream
}

func (x *clusterServiceHeartbeatServer) Send(m *HeartbeatPong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clusterServiceHeartbeatServer) Recv() (*HeartbeatPing, error) {
	m := new(HeartbeatPing)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegisterClusterServiceServer registers the ClusterServiceServer with the grpc.Server.
func RegisterClusterServiceServer(s *grpc.Server, srv ClusterServiceServer) {
	s.RegisterService(&_ClusterService_serviceDesc, srv)
}

var _ClusterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _ClusterService_RegisterWorker_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ClusterService_GetMetrics_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _ClusterService_ExecuteCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Heartbeat",
			Handler:       _ClusterService_Heartbeat_Handler,
			ServerStreams:  true,
			ClientStreams:  true,
		},
	},
	Metadata: "proto/cluster.proto",
}

func _ClusterService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/RegisterWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).RegisterWorker(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/GetMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetMetrics(ctx, req.(*MetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/ExecuteCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).ExecuteCommand(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterServiceServer).Heartbeat(&clusterServiceHeartbeatServer{stream})
}
