#!/bin/bash
################################################################################
# AetherFlow Installation Script
#
# GitHub:   https://github.com/McEveritts/AetherFlow
# Author:   McEveritts
# URL:      https://aetherflow.io
#
# AetherFlow Copyright (C) 2017-2022 AetherFlow.io
# Licensed under GNU General Public License v3.0 GPL-3 (in short)
#
#   You may copy, distribute and modify the software as long as you track
#   changes/dates in source files. Any modifications to our software
#   including (via compiler) GPL-licensed code must also be made available
#   under the GPL along with build & install instructions.
#
#################################################################################
#Script Console Colors
black=$(tput setaf 0)
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
# Ensure system binaries are in PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

on_red=$(tput setab 1)
on_green=$(tput setab 2)
on_magenta=$(tput setab 5)
bold=$(tput bold)
standout=$(tput smso)
normal=$(tput sgr0)
alert=${white}${on_red}
title=${standout}
repo_title=${black}${on_green}
message_title=${white}${on_magenta}
#################################################################################

# Check if running from setup directory or installed location
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Auto-Bootstrap if downloaded as a single script via the GitHub one-liner
if [[ ! -d "${SCRIPT_DIR}/modules" ]]; then
    echo "Bootstrapping AetherFlow Installer Environment..."
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y >/dev/null 2>&1
    apt-get install -y git bc curl >/dev/null 2>&1
    
    rm -rf /opt/MediaNexus
    git clone https://github.com/McEveritts/AetherFlow.git /opt/MediaNexus >/dev/null 2>&1
    
    # Relaunch from the proper directory
    cd /opt/MediaNexus/setup || exit 1
    exec bash AetherFlow-Setup "$@"
    exit 0
fi

# We are in the correct bootstrapped setup directory
BASE_DIR="$(dirname "${SCRIPT_DIR}")"
local_setup="${SCRIPT_DIR}/"
local_packages="${BASE_DIR}/packages/"
local_rutorrent="${BASE_DIR}/rutorrent/"
local_rplugins="${BASE_DIR}/rtplugins/"
local_dashboard="${BASE_DIR}/dashboard/"

# Load Modules
for module in "${SCRIPT_DIR}/modules/"*.sh; do
    # shellcheck disable=1090
    source "$module"
done


clear

# shellcheck disable=2312,2243,1003
spinner() {
	local pid=$1
	local delay=0.25
	local spinstr='|/-\'
	while [[ "$(ps a | awk '{print $1}' | grep ${pid})" ]]; do
		local temp=${spinstr#?}
		printf " [${bold}${yellow}%c${normal}]  " "${spinstr}"
		local spinstr=${temp}${spinstr%"${temp}"}
		sleep "${delay}"
		printf "\b\b\b\b\b\b"
	done
	printf "    \b\b\b\b"
	echo -ne "${OK}"
}
if [[ ! -d "${local_setup}" ]]; then
    echo "Critical Error: Setup paths failed to resolve."
    exit 1
fi
# shellcheck disable=2312
IFACE=$(ip link show | grep -i broadcast | grep -m1 UP | cut -d: -f 2 | cut -d@ -f 1 | sed -e 's/ //g')
PORT=$(shuf -i 2000-61000 -n 1)
PORTEND=$((${PORT} + 1500))
# shellcheck disable=2312
while [[ "$(netstat -ln | grep ':'"${PORT}"'' | grep -c 'LISTEN')" -eq "1" ]]; do PORT="$(shuf -i 2000-61000 -n 1)"; done
RPORT=$(shuf -i 2000-61000 -n 1)
# shellcheck disable=2312
while [[ "$(netstat -ln | grep ':'"${RPORT}"'' | grep -c 'LISTEN')" -eq "1" ]]; do RPORT="$(shuf -i 2000-61000 -n 1)"; done
S=$(date +%s)
OK=$(echo -e "[ ${bold}${green}DONE${normal} ]")
genpass=$(_string)
HTPASSWD="/etc/htpasswd"
rutorrent="/srv/rutorrent/"
REALM="rutorrent"
AUTODLPASSWORD=$(_string)
AUTODLPORT=$(shuf -i 2000-61000 -n 1)
# shellcheck disable=2312
ip=$(ip route get 8.8.8.8 | awk 'NR==1 {print $7}')
export DEBIAN_FRONTEND=noninteractive
cd

# AetherFlow STRUCTURE
_bashrc
_intro
_checkroot
_logcheck
_checkkernel
_hostname
_askquota
_askcontinue
_ssdpblock
_locale
clear

_askpartition
_ask10g
_askrtorrent
_askdeluge
_asktr
apt-get install -q -y curl >>"${OUTTO}" 2>&1
_askqb
_askdashtheme
_adduser
_askffmpeg
_askvsftpd
_denyhosts
_askbbr
clear

echo
echo ""
echo "${bold}${magenta}AetherFlow will now install, this may take between${normal}"
echo "${bold}${magenta}10 and 45 minutes depending on your systems specs${normal}"
echo ""
echo -n "Pulling AetherFlow Ecosystem ... "
_repos &
spinner $!
echo
echo -n "Updating system ... "
_updates &
spinner $!
echo
echo -n "Installing all needed dependencies ... "
_depends &
spinner $!
echo
if [[ ${RTVERSION} != 0.9.7 ]]; then
	echo -n "Installing openssl ... "
	_openssl &
	spinner $!
	echo
fi
echo -n "Setting up system executables ... "
_syscommands &
spinner $!
echo
echo -n "Building required user directories ... "
_skel &
spinner $!
echo
if [[ ${quota} == "yes" ]]; then
	echo -n "Setting up quotas for ${green}/(${primaryroot})${normal} mount ... "
	_qmount &
	spinner $!
	echo
fi
echo -n "Setting up Limited Shell environment ... "
_lshell &
spinner $!
echo
if [[ ${ffmpeg} == "yes" ]]; then
	echo -n "Building ffmpeg from source for screenshots ... "
	_ffmpeg &
	spinner $!
	echo
fi
_apachesudo
echo -n "Installing xmlrpc-c ... "
_xmlrpc &
spinner $!
echo
echo -n "Installing libtorrent-rakshasa ${green}${LTORRENT}${normal} ... "
_libtorrent &
spinner $!
echo
echo -n "Installing rtorrent-${green}${RTVERSION}${normal} ... "
_rtorrent &
spinner $!
echo
echo -n "Installing rutorrent into /srv ... "
_rutorrent &
spinner $!
echo
echo -n "Installing rutorrent plugins ... "
_rutorrent-plugins &
spinner $!
echo
if [[ ${DELUGE} != NO ]]; then
	echo -n "Installing deluge ... "
	_deluge &
	spinner $!
	echo
	echo -n "Setting up deluge Web Reverse Proxy ... "
	_insdwApache &
	spinner $!
	echo
fi
if [[ ${tr} == "yes" ]]; then
	echo -n "Configuring Transmisson ... "
	_insTr &
	spinner $!
	echo
	echo -n "Installing Transmisson Web Control ... "
	_insTrWeb &
	spinner $!
	echo
	echo -n "Setting up Transmission Reverse Proxy ... "
	_insTrApache &
	spinner $!
	echo
fi
if [[ ${QBVERSION} != "no" ]]; then
	echo -n "Installing qBittorrent ... "
	_qbittorrent &
	spinner $!
	echo
	echo -n "Setting up qBittorrent Reverse Proxy ... "
	_insqBApache &
	spinner $!
	echo
fi
echo -n "Installing mktorrent from source ... "
_mktorrent &
spinner $!
echo
echo -n "Installing AetherFlow dashboard ... "
_dashboard &
spinner $!
echo
echo -n "Installing Go and Node.js for modern stack ... "
_install_go &
spinner $!
_install_node &
spinner $!
echo
echo -n "Building Next.js and Go API ... "
_build_modern_stack &
spinner $!
echo
echo -n "Setting up seedbox.conf for apache ... "
_apacheconf &
spinner $!
echo
echo -n "Fix SSL Cert for apache ... "
_fix_cert &
spinner $!
echo
echo -n "Installing .rtorrent.rc for ${username} ... "
_rconf &
spinner $!
echo
echo -n "Adjusting fileupload & filemanager plugins ... "
_plugins &
spinner $!
echo
echo -n "Installing autodl-irssi ... "
_autodl &
spinner $!
echo
echo -n "Making ${username} directory structure ... "
_makedirs &
spinner $!
echo
echo -n "Writing ${username} rutorrent config.php file ... "
_ruconf &
spinner $!
echo
echo -n "Installing vsftpd ... "
_installftpd &
spinner $!
echo
echo -n "Setting up vsftpd ... "
_ftpdconfig &
spinner $!
echo
_quickstats
_quickconsole
echo -n "Setting irssi/rtorrent to start on boot ... "
_boot &
spinner $!
echo
echo -n "Setting permissions on ${username} ... "
_perms &
spinner $!
echo
if [[ ${bbr} == "yes" ]]; then
	echo -n "install BBR ... "
	_insbbr &
	spinner $!
	echo
fi
# shellcheck disable=2312
if lspci | grep -i bcm >/dev/null; then
	echo -n "Installing firmware for BCM NIC ... "
	_insbcm &
	spinner $!
	echo
fi
cd
E=$(date +%s)
DIFF=$(echo "${E}" - "${S}" | bc)
FIN=$(echo "${DIFF}" / 60 | bc)
clear
_finished

